// <auto-generated />
using System;
using Firefly.Signal.Ai.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Firefly.Signal.Ai.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiDbContext))]
    [Migration("20260418092713_AddMqRequestCorrelationUniqueness")]
    partial class AddMqRequestCorrelationUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Firefly.Signal.Ai.Domain.AiMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("ai_messages", "ai");
                });

            modelBuilder.Entity("Firefly.Signal.Ai.Domain.AiRequest", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CallerService")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplyEventType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("SystemPromptMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserPromptMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("SystemPromptMessageId");

                    b.HasIndex("UserPromptMessageId");

                    b.ToTable("ai_requests", "ai");
                });

            modelBuilder.Entity("Firefly.Signal.Ai.Domain.AiResponse", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AiRequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("AiResponseMessageId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AiRequestId")
                        .IsUnique();

                    b.HasIndex("AiResponseMessageId");

                    b.ToTable("ai_responses", "ai");
                });

            modelBuilder.Entity("Firefly.Signal.Ai.Domain.AiRequest", b =>
                {
                    b.HasOne("Firefly.Signal.Ai.Domain.AiMessage", "SystemPromptMessage")
                        .WithMany()
                        .HasForeignKey("SystemPromptMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Firefly.Signal.Ai.Domain.AiMessage", "UserPromptMessage")
                        .WithMany()
                        .HasForeignKey("UserPromptMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SystemPromptMessage");

                    b.Navigation("UserPromptMessage");
                });

            modelBuilder.Entity("Firefly.Signal.Ai.Domain.AiResponse", b =>
                {
                    b.HasOne("Firefly.Signal.Ai.Domain.AiRequest", null)
                        .WithOne("Response")
                        .HasForeignKey("Firefly.Signal.Ai.Domain.AiResponse", "AiRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Firefly.Signal.Ai.Domain.AiMessage", "Message")
                        .WithMany()
                        .HasForeignKey("AiResponseMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Firefly.Signal.Ai.Domain.AiRequest", b =>
                {
                    b.Navigation("Response");
                });
#pragma warning restore 612, 618
        }
    }
}
