using System.Linq.Expressions;
using Firefly.Signal.JobSearch.Contracts.Requests;
using Firefly.Signal.JobSearch.Contracts.Responses;
using Firefly.Signal.JobSearch.Domain;

namespace Firefly.Signal.JobSearch.Application.Mappers;

internal static class JobResponseMappers
{
    public static Expression<Func<JobPosting, CreateJobRequest>> ToExportRequest()
        => job => new CreateJobRequest(
            job.JobRefreshRunId,
            job.SourceName,
            job.SourceJobId,
            job.SourceAdReference,
            job.Title,
            job.Description,
            job.Summary,
            job.Url,
            job.Company,
            job.CompanyDisplayName,
            job.CompanyCanonicalName,
            job.Postcode,
            job.LocationName,
            job.LocationDisplayName,
            job.LocationAreaJson,
            job.Latitude,
            job.Longitude,
            job.CategoryTag,
            job.CategoryLabel,
            job.SalaryMin,
            job.SalaryMax,
            job.SalaryCurrency,
            job.SalaryIsPredicted,
            job.ContractTime,
            job.ContractType,
            job.IsFullTime,
            job.IsPartTime,
            job.IsPermanent,
            job.IsContract,
            job.IsRemote,
            job.PostedAtUtc,
            job.ImportedAtUtc,
            job.LastSeenAtUtc,
            job.IsHidden,
            job.RawPayloadJson);

    public static Expression<Func<JobPosting, JobDetailsResponse>> ToDetailsResponse()
        => job => new JobDetailsResponse(
            job.Id,
            job.JobRefreshRunId,
            job.SourceName,
            job.SourceJobId,
            job.SourceAdReference,
            job.Title,
            job.Description,
            job.Summary,
            job.Url,
            job.Company,
            job.CompanyDisplayName,
            job.CompanyCanonicalName,
            job.Postcode,
            job.LocationName,
            job.LocationDisplayName,
            job.LocationAreaJson,
            job.Latitude,
            job.Longitude,
            job.CategoryTag,
            job.CategoryLabel,
            job.SalaryMin,
            job.SalaryMax,
            job.SalaryCurrency,
            job.SalaryIsPredicted,
            job.ContractTime,
            job.ContractType,
            job.IsFullTime,
            job.IsPartTime,
            job.IsPermanent,
            job.IsContract,
            job.IsRemote,
            job.PostedAtUtc,
            job.ImportedAtUtc,
            job.LastSeenAtUtc,
            job.IsHidden,
            job.RawPayloadJson);

    public static JobDetailsResponse ToDetailsResponse(JobPosting job)
        => new(
            job.Id,
            job.JobRefreshRunId,
            job.SourceName,
            job.SourceJobId,
            job.SourceAdReference,
            job.Title,
            job.Description,
            job.Summary,
            job.Url,
            job.Company,
            job.CompanyDisplayName,
            job.CompanyCanonicalName,
            job.Postcode,
            job.LocationName,
            job.LocationDisplayName,
            job.LocationAreaJson,
            job.Latitude,
            job.Longitude,
            job.CategoryTag,
            job.CategoryLabel,
            job.SalaryMin,
            job.SalaryMax,
            job.SalaryCurrency,
            job.SalaryIsPredicted,
            job.ContractTime,
            job.ContractType,
            job.IsFullTime,
            job.IsPartTime,
            job.IsPermanent,
            job.IsContract,
            job.IsRemote,
            job.PostedAtUtc,
            job.ImportedAtUtc,
            job.LastSeenAtUtc,
            job.IsHidden,
            job.RawPayloadJson);
}
