namespace Firefly.Signal.JobSearch.Application;

public sealed record JobDetailsResponse(
    long Id,
    long? JobRefreshRunId,
    string SourceName,
    string SourceJobId,
    string? SourceAdReference,
    string Title,
    string Description,
    string Summary,
    string Url,
    string Company,
    string? CompanyDisplayName,
    string? CompanyCanonicalName,
    string Postcode,
    string LocationName,
    string? LocationDisplayName,
    string? LocationAreaJson,
    decimal? Latitude,
    decimal? Longitude,
    string? CategoryTag,
    string? CategoryLabel,
    decimal? SalaryMin,
    decimal? SalaryMax,
    string? SalaryCurrency,
    bool? SalaryIsPredicted,
    string? ContractTime,
    string? ContractType,
    bool IsFullTime,
    bool IsPartTime,
    bool IsPermanent,
    bool IsContract,
    bool IsRemote,
    DateTime PostedAtUtc,
    DateTime ImportedAtUtc,
    DateTime LastSeenAtUtc,
    bool IsHidden,
    string RawPayloadJson);

public sealed record GetJobsPageRequest(
    int PageIndex = 0,
    int PageSize = 20,
    string? Keyword = null,
    string? Company = null,
    string? Postcode = null,
    string? Location = null,
    string? SourceName = null,
    string? CategoryTag = null,
    bool? IsHidden = false);

public sealed record PagedJobsResponse(
    int PageIndex,
    int PageSize,
    long TotalCount,
    IReadOnlyList<JobDetailsResponse> Jobs);

public sealed record CreateJobRequest(
    long? JobRefreshRunId,
    string SourceName,
    string SourceJobId,
    string? SourceAdReference,
    string Title,
    string Description,
    string Summary,
    string Url,
    string Company,
    string? CompanyDisplayName,
    string? CompanyCanonicalName,
    string Postcode,
    string LocationName,
    string? LocationDisplayName,
    string? LocationAreaJson,
    decimal? Latitude,
    decimal? Longitude,
    string? CategoryTag,
    string? CategoryLabel,
    decimal? SalaryMin,
    decimal? SalaryMax,
    string? SalaryCurrency,
    bool? SalaryIsPredicted,
    string? ContractTime,
    string? ContractType,
    bool IsFullTime,
    bool IsPartTime,
    bool IsPermanent,
    bool IsContract,
    bool IsRemote,
    DateTime PostedAtUtc,
    DateTime ImportedAtUtc,
    DateTime LastSeenAtUtc,
    bool IsHidden,
    string RawPayloadJson);

public sealed record UpdateJobRequest(
    long? JobRefreshRunId,
    string SourceName,
    string SourceJobId,
    string? SourceAdReference,
    string Title,
    string Description,
    string Summary,
    string Url,
    string Company,
    string? CompanyDisplayName,
    string? CompanyCanonicalName,
    string Postcode,
    string LocationName,
    string? LocationDisplayName,
    string? LocationAreaJson,
    decimal? Latitude,
    decimal? Longitude,
    string? CategoryTag,
    string? CategoryLabel,
    decimal? SalaryMin,
    decimal? SalaryMax,
    string? SalaryCurrency,
    bool? SalaryIsPredicted,
    string? ContractTime,
    string? ContractType,
    bool IsFullTime,
    bool IsPartTime,
    bool IsPermanent,
    bool IsContract,
    bool IsRemote,
    DateTime PostedAtUtc,
    DateTime ImportedAtUtc,
    DateTime LastSeenAtUtc,
    bool IsHidden,
    string RawPayloadJson);

public sealed record HideJobsResponse(
    int HiddenCount,
    IReadOnlyList<long> HiddenIds,
    IReadOnlyList<long> MissingIds);

public sealed record DeleteJobsResponse(
    int DeletedCount,
    IReadOnlyList<long> DeletedIds,
    IReadOnlyList<long> MissingIds,
    IReadOnlyList<long> NotHiddenIds);

public sealed record BulkJobIdsRequest(IReadOnlyList<long> Ids);
